# [context.production] (branch: master)
# [context.deploy-preview]
# [context.branch-deploy]
# branch: staging
[build]
  base = ""
  command = "npm run build"
  publish = "dist"

# branch: prod-archives-2016
[context.prod-archives-2016]
  command = "npm run build:deploy"
